# Generated by Django 3.1.7 on 2021-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.FileField(upload_to='files'),
        ),
    ]
